export function handleException(status) {
  console.log("error", status);
}